multiplayer_chess/urls.py
from unicodedata import name
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'multiplayer_chess'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('register/', views.registerView, name='register'),
    path('home/', views.home, name='home'),
    path('gameroom/', views.gameroom, name='gameroom'),
    path('friends/', views.friends, name='friends'),
    path('play_with_friend/<str:friend_name>/',
         views.play_with_friend, name='play_with_friend'),
    path('accept_friend_request/<str:friend_name>/',
         views.accept_friend_request, name='accept_friend_request'),
    path('reject_friend_request/<str:friend_name>/',
         views.reject_friend_request, name='reject_friend_request'),
    path('player_exists/<str:friend_name>/',
         views.player_exists, name='player_exists'),
    path('send_request/<str:friend_name>/',
         views.send_request, name="send_request"),
    path('player_info/', views.player_info, name='player_info'),
    path('games_archive', views.games_archive, name='games_archive')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project_chess/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('multiplayer_chess.urls'))
]

multiplayer_chess/models.py
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.db.models.fields import BooleanField

# Create your models here.


class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    friends = models.ManyToManyField(
        "Player", blank=True, related_name="Friends")
    is_online = models.BooleanField(default=False)
    is_ingame = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.user.username


class Friend_Request(models.Model):
    from_user = models.ForeignKey(
        Player, related_name="from_user", on_delete=CASCADE)
    to_user = models.ForeignKey(
        Player, related_name="to_user", on_delete=CASCADE)


class Gameroom(models.Model):
    room_name = models.CharField(max_length=50)
    players = models.ManyToManyField(Player, related_name="played_in")
    active = models.BooleanField(default=True)
    private = models.BooleanField(default=False)
    time = models.DateTimeField(auto_now_add=True)
    winner = models.ForeignKey(
        Player, on_delete=CASCADE, related_name="winner", null=True)

    def __str__(self) -> str:
        return str(self.room_name) + str(self.pk)

multiplayer_chess/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


# class NewUserForm(UserCreationForm):
#     def __init__(self, *args, **kwargs):
#         super(NewUserForm, self).__init__(*args, **kwargs)
#         for visible in self.visible_fields():
#             visible.field.widget.attrs['class'] = 'form-control form-control-lg'
#     email = forms.EmailField(required=True)

#     class Meta:
#         model = User
#         fields = ("username", "email", "password1", "password2")

multiplayer_chess/views.py
from urllib.request import Request
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from matplotlib.style import use
from django.db.models import Q
from multiplayer_chess.models import Friend_Request, Player
from .forms import LoginForm, RegisterForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    if request.user.is_authenticated:
        return redirect('multiplayer_chess:home')
    return redirect('multiplayer_chess:login')


def loginView(request):
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("multiplayer_chess:home")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = LoginForm()
    return render(request=request, template_name="multiplayer_chess/login.html", context={"login_form": form})


def logoutView(request):
    logout(request)
    return redirect("multiplayer_chess:login")


def registerView(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        try:
            user = form.save()
            Player.objects.create(user=user)
            login(request, user)
            messages.success(request, "Registration successful")
            return redirect("multiplayer_chess:home")
        except Exception as e:
            messages.error(request, str(e))
    form = RegisterForm()
    return render(request=request, template_name="multiplayer_chess/register.html", context={"register_form": form})


@login_required(login_url='/login')
def home(request):
    p = Player.objects.get(user=request.user)
    return render(request=request, template_name='multiplayer_chess/home.html', context={
        'recent_games': getPastGames(p, 5)
    })


@login_required(login_url='/login')
def gameroom(request):
    return render(request=request, template_name="multiplayer_chess/gameroom.html", context={
        "game_type": 0
    })


@login_required(login_url='/login')
def play_with_friend(request, friend_name):
    return render(request=request, template_name="multiplayer_chess/gameroom.html", context={
        "game_type": 1,
        "friend_name": friend_name
    })


@login_required(login_url='/login')
def friends(request):

    player = Player.objects.get(user=request.user)
    friend_requests = []
    friends_list = []
    friends_list = player.friends.all().order_by('-is_online')
    friend_requests = Friend_Request.objects.filter(to_user=player)
    return render(request=request, template_name="multiplayer_chess/friends.html", context={
        'friend_requests': friend_requests,
        'friends_list': friends_list
    })


@login_required(login_url='/login')
def accept_friend_request(request, friend_name):
    player = Player.objects.get(user=request.user)
    friend = Player.objects.get(user=User.objects.get(username=friend_name))
    player.friends.add(friend)
    friend.friends.add(player)

    Friend_Request.objects.filter(from_user=friend, to_user=player).delete()
    return redirect('multiplayer_chess:friends')


@login_required(login_url='/login')
def reject_friend_request(request, friend_name):
    player = Player.objects.get(user=request.user)
    friend = Player.objects.get(user=User.objects.get(username=friend_name))
    Friend_Request.objects.filter(from_user=friend, to_user=player).delete()
    return redirect('multiplayer_chess:friends')


@login_required(login_url='/login')
def player_exists(request, friend_name):
    msg = "User found"
    exists = True
    if not User.objects.filter(username=friend_name).exists():
        msg = "User not found"
        exists = False
    elif request.user.username == friend_name:
        msg = "You"
        exists = False
    return JsonResponse({
        "exists": exists,
        "msg": msg
    })


@login_required(login_url='/login')
def send_request(request, friend_name):
    msg = ""
    from_user = Player.objects.get(user=request.user)
    to_user = Player.objects.get(user=User.objects.get(username=friend_name))
    print(from_user, to_user)
    if(Friend_Request.objects.filter(to_user=to_user, from_user=from_user).exists()):
        msg = "Request already sent"
    elif to_user in from_user.friends.all():
        msg = "Already a friend"
    else:
        Friend_Request.objects.create(from_user=from_user, to_user=to_user)
        msg = "Request sent"
    return JsonResponse({"msg": msg})


@login_required(login_url='/login')
def player_info(request):
    p = Player.objects.get(user=request.user)

    rating = 0
    total_games = p.played_in.all().count()
    games_won = p.winner.all().count()
    if total_games == 0:
        win_percent = 0
    else:
        win_percent = games_won/total_games * 100

    friends_info = {}
    friends = p.friends.all()
    for f in friends:
        w = p.played_in.filter(winner=p).intersection(
            f.played_in.all()).count()
        l = p.played_in.filter(winner=f).intersection(
            f.played_in.all()).count()
        d = p.played_in.filter(winner=None).intersection(
            f.played_in.all()).count()
        friends_info[f] = {'won': w, 'lost': l, 'draw': d}

    context = {
        'rating': rating,
        'total_games': total_games,
        'win_percent': str(round(win_percent, 2)),
        'recent_games': getPastGames(p, 5),
        'friends_info': friends_info
    }
    return render(request=request, template_name='multiplayer_chess/profile.html', context=context)


def getPastGames(player, n):  # -1 for all games
    if n == -1:
        recent_games = player.played_in.all().order_by('-time')
    else:
        recent_games = player.played_in.all().order_by('-time')[:n]
    recent_games_arr = []
    for game in recent_games:
        opponent = game.players.filter(~Q(user=player.user))[0]
        result = game.winner == player
        recent_games_arr.append((opponent, result))

    return recent_games_arr


def games_archive(request):
    p = Player.objects.get(user=request.user)
    return render(request=request, template_name='multiplayer_chess/games_archive.html', context={
        'all_games': getPastGames(p, -1)
    })

multiplayer_chess/templates/multiplayer_chess/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'multiplayer_chess/main.css' %}"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'multiplayer_chess/base.css' %}">
    {% block css %}
    {% endblock %}
    {% block title %}
    {% endblock %}
</head>
<body style="background-color: rgb(63, 63, 63);">
      <div>
        {% block navbar %}
        {% endblock %}
      </div>
      <div>
          {% block content %}
          {% endblock %}
      </div>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

multiplayer_chess/templates/multiplayer_chess/friends.html
{% extends 'multiplayer_chess/base.html' %}
{% load static %}
{% block title %}
    <title>Friends</title>
{% endblock %}
{% block navbar %}
    {%include 'multiplayer_chess/navbar.html'%}
{% endblock %}
{% block content %}

    {% for fr in friend_requests %}
    <div class="container">
        <span>{{fr.from_user}}</span>
        <div class="btn-group">
            <a class="btn btn-success" href="{% url 'multiplayer_chess:accept_friend_request' friend_name=fr.from_user %}">Accept</a>
            <a class="btn btn-danger" href="{% url 'multiplayer_chess:reject_friend_request' friend_name=fr.from_user %}">Reject</a>
        </div>
    </div>
    {% endfor %}
    
    <div class="d-flex flex-column justify-content-center align-items-center py-4">
        {% for friend in friends_list %}
        <div class="container rounded shadow m-3 d-flex p-3 align-items-center bg-light">
            <div class="w-50">
                {% if friend.is_online %}
                    <span class="badge bg-success mx-3">Online</span>
                {% else %}
                    <span class="badge bg-dark mx-3">Offline</span>
                {% endif %}
                {{ friend }}
            </div>
            <a class="container btn w-25 primary_bg" href="{% url 'multiplayer_chess:play_with_friend' friend_name=friend.user.username %}">Challenge</a>
        </div>
        {% endfor %}
    </div>
    <div class="d-flex flex-column justify-content-center align-items-center">
        <button type="button" class="container btn primary_bg" data-toggle="modal" data-target="#addFriendModal">Add friend</button>
    </div>
    <div class="modal fade" id="addFriendModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Add friend</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <div class="input-group mb-3">
                    <input id="friendSearch" type="text" class="form-control" placeholder="Friend's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-outline-primary" id="friendSearchButton" type="button">Search</button>
                    </div>
                </div>
                <div id="searchResultContainer" class="d-none">
                    <div class="container w-50" id="searchResultName"></div>
                    <button class="w-50 btn btn-success" id="btnSendRequest">Send Request</button>
                </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
    </div>
    

    <script>
    function getPlayerExistsUrl(friend_name){
        return "{% url 'multiplayer_chess:player_exists' friend_name=12345 %}".replace(/12345/, friend_name.toString())
    }
    function getSendRequestUrl(friend_name){
        return "{% url 'multiplayer_chess:send_request' friend_name=12345 %}".replace(/12345/, friend_name.toString())
    }
    function getFriendMatchUrl(friend_name) {
            return "{% url 'multiplayer_chess:play_with_friend' friend_name=12345 %}".replace(/12345/, friend_name.toString())
    }
        // function declared here because django template scripting tags cannot be used in static files
    
    </script>

    <script src="{% static 'multiplayer_chess/friends.js' %}"></script>
    <script src="{% static 'multiplayer_chess/connection.js' %}"></script>
{% endblock %}

multiplayer_chess/templates/multiplayer_chess/games_archive.html
{% extends 'multiplayer_chess/base.html' %}
{% load static %}
{% block title %}
    <title>Games Archive</title>
{% endblock %}
{% block navbar %}
    {%include 'multiplayer_chess/navbar.html'%}
{% endblock %}
{% block content %}

<div class="container text-white primary_bg rounded-3 my-5 d-flex justify-content-between align-items-center">
    <div class="p-2 w-100" style="font-size: 2rem;" >Games Archive</div>
</div>
<div class="container text-white">
    {% for opponent, result in all_games %}
        <div class="d-flex justify-content-between p-2">
            <div class="display-7">{{opponent}}</div>
            {% if result %}
                <div class="badge bg-success">Won</div>
            {% else %}
                <div class="badge bg-danger">Lost</div>
            {% endif %}
        </div>
        <hr>
    {% endfor %}
</div>

{% endblock %}

multiplayer_chess/templates/multiplayer_chess/home.html
{% extends 'multiplayer_chess/base.html' %}
{% load static %}
{% block title %}
    <title>Home</title>
{% endblock %}
{% block navbar %}
    {%include 'multiplayer_chess/navbar.html'%}
{% endblock %}
{% block content %}
    <div class="container my-3">
        <div class="row justify-content-around">
            <div class="col-9 my-3 col-sm-5">
                <div class="card">
                    <img style="max-height: 450px;" src="{% static 'multiplayer_chess/images/chess_random.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'multiplayer_chess:gameroom' %}" class="container btn primary_bg stretched-link">Play random</a>
                    </div>
                </div>
            </div>
            <div class="col-9 my-3 col-sm-5">
                <div class="card">
                    <img style="max-height: 450px;" src="{% static 'multiplayer_chess/images/chess_friend.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'multiplayer_chess:friends' %}" class="container btn primary_bg stretched-link">Play with friends</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'multiplayer_chess/recent_games.html' %}

    <script>
        // function declared here because django template scripting tags cannot be used in static files
        function getFriendMatchUrl(friend_name) {
            return "{% url 'multiplayer_chess:play_with_friend' friend_name=12345 %}".replace(/12345/, friend_name.toString())
        }
    </script>
    <script src="{% static 'multiplayer_chess/connection.js' %}"></script>
{% endblock %}

multiplayer_chess/templates/multiplayer_chess/login.html
{% extends 'multiplayer_chess/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'multiplayer_chess/form.css' %}">
{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<section>
    <div class="container py-3 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">
              <div class="col-md-6 col-lg-5 d-none d-md-flex">
                <img
                  src="https://images.pexels.com/photos/4973821/pexels-photo-4973821.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
                  alt="login form"
                  class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
                />
              </div>
              <div class="col-md-6 col-lg-7 d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">
  
                  <form method="post">
                    {% csrf_token %}
                    <div class="d-flex align-items-center mb-3 pb-1">
                      <span class="h1 fw-bold mb-0">&#9823; Chess</span>
                    </div>
  
                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>
  
                    <div class="form-outline mb-4">
                      <!-- <input type="email" id="form2Example17" class="form-control form-control-lg" />
                      <label class="form-label" for="form2Example17">Email address</label> -->

                      <label class="form-label" for="id_username">Username</label>
                        {{ login_form.username }}
                    </div>
  
                    <div class="form-outline mb-4">
                      <!-- <input type="password" id="form2Example27" class="form-control form-control-lg" />
                      <label class="form-label" for="form2Example27">Password</label> -->

                      <label class="form-label" for="id_password">Password</label>
                        {{ login_form.password }}
                    </div>
  
                    <div class="pt-1 mb-4 d-grid">
                      <button class="btn btn-dark btn-lg" type="submit">Login</button>
                    </div>
  
                    <a class="small text-muted" href="#!">Forgot password?</a>
                    <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a style="color: #393f81;" href="{% url 'multiplayer_chess:register' %}">Register here</a></p>
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

multiplayer_chess/templates/multiplayer_chess/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark primary_bg" style="z-index: 1;">
    <a class="navbar-brand" href="{% url 'multiplayer_chess:home' %}">&#9823; Chess</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link mx-4" href="{% url 'multiplayer_chess:player_info' %}">{{ request.user }}</a>
        <a class="nav-item nav-link mx-4" href="{% url 'multiplayer_chess:logout' %}">logout</a>
      </div>
    </div>
  </nav>

multiplayer_chess/templates/multiplayer_chess/profile.html
{% extends 'multiplayer_chess/base.html' %}
{% load static %}
{% block title %}
    <title>{{ request.user.username }}</title>
{% endblock %}
{% block navbar %}
    {%include 'multiplayer_chess/navbar.html'%}
{% endblock %}
{% block content %}
<div class="container sm-w-75">
    <div class="container primary_bg w-100">
        <div class="row container d-flex flex-column flex-sm-row justify-content-between align-items-center text-white my-3 w-100">
            <div class="col display-3 p-3 m-3 d-flex justify-content-center">{{ request.user.username }}</div>
            <div class="col d-flex flex-column p-3">
                <div class="d-flex justify-content-between">
                    <div>Rating</div>
                    <div>{{rating}}</div>
                </div>
                <div class="d-flex justify-content-between">
                    <div>Total games</div>
                    <div>{{total_games}}</div>
                </div>
                <div class="d-flex justify-content-between">
                    <div>Win percentage</div>
                    <div>{{win_percent}} %</div>
                </div>
            </div>
        </div>
    </div>
    
    {% include 'multiplayer_chess/recent_games.html' %}

    <div class="container text-white primary_bg rounded-3">
        <div class="p-2 my-3 w-100" style="font-size: 2rem;">Friends</div>
    </div>
    <div class="container text-white">
        {% for friend, info in friends_info.items %}
            <div class="d-flex justify-content-between p-2">
                <div>{{friend}}</div>
                <div>
                    <div class="badge bg-success">{{info.won}} W</div>
                    <div class="badge bg-danger">{{info.lost}} L</div>
                    <div class="badge">{{info.draw}} D</div>
                </div>
            </div>
            <hr>
        {% endfor %}
    </div>
</div>
<script>
    // function declared here because django template scripting tags cannot be used in static files
    function getFriendMatchUrl(friend_name) {
        return "{% url 'multiplayer_chess:play_with_friend' friend_name=12345 %}".replace(/12345/, friend_name.toString())
    }
</script>

<script src="{% static 'multiplayer_chess/connection.js' %}"></script>

    

{% endblock %}

multiplayer_chess/templates/multiplayer_chess/recent_games.html
<div class="container text-white primary_bg rounded-3 my-5 d-flex justify-content-between align-items-center">
    <div class="p-2 w-100" style="font-size: 2rem;" >Recent games</div>
    <a href="{% url 'multiplayer_chess:games_archive' %}" class=" p-3 user-select-none" style="text-decoration: none; color: white;" data-bs-toggle="tooltip" data-bs-placement="top" title="Games archive">></a>
</div>
<div class="container text-white">
    {% for opponent, result in recent_games %}
        <div class="d-flex justify-content-between p-2">
            <div class="display-7">{{opponent}}</div>
            {% if result %}
                <div class="badge bg-success">Won</div>
            {% else %}
                <div class="badge bg-danger">Lost</div>
            {% endif %}
        </div>
        <hr>
    {% endfor %}
</div>

multiplayer_chess/templates/multiplayer_chess/register.html
{% extends 'multiplayer_chess/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'multiplayer_chess/form.css' %}">
{% endblock %}

{% block content %}



<section>
    <div class="container py-3 h-100" >
      <div class="row d-flex justify-content-center align-items-center h-100" >
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">
              <div class="col-md-6 col-lg-5 d-none d-md-flex">
                <img
                  src="https://images.unsplash.com/photo-1619163413327-546fdb903195?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"
                  alt="login form"
                  class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
                />
              </div>
              <div class="col-md-6 col-lg-7 d-flex align-items-center">
                <div class="card-body m-0 p-3 p-lg-5 text-black">
  
                  <form method="post">
                    {% csrf_token %}
                    <div class="d-flex align-items-center mb-2 pb-1">
                      <span class="h1 fw-bold mb-0">&#9823; Chess</span>
                    </div>
  
                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Create new account</h5>
  
                    <div class="form-outline mb-2">

                      <label class="form-label" for="id_username">Username</label>
                        {{ register_form.username }}
                    </div>

                    <div class="form-outline mb-2">
  
                        <label class="form-label" for="id_username">Email</label>
                          {{ register_form.email }}
                      </div>
  
                    <div class="form-outline mb-2">

                      <label class="form-label" for="id_password1">Password</label>
                        {{ register_form.password1 }}
                    </div>

                    <div class="form-outline mb-2">
  
                        <label class="form-label" for="id_password2">Confirm Password</label>
                          {{ register_form.password2 }}
                      </div>
  
                    <div class="pt-1 mb-4 d-grid">
                      <button class="btn btn-dark btn-lg" type="submit">Register</button>
                    </div>
                    <p class="mb-2 pb-lg-2" style="color: #393f81;">Have an account? <a style="color: #393f81;" href="{% url 'multiplayer_chess:login' %}">Login</a></p>
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}


<!-- {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'multiplayer_chess/form.css' %}">
</head>
<body>
    <div class="">
        <form method="POST" class="container" >
            {% csrf_token %}
            <div class="header_text">
                <h2>Create a new account</h2>
            </div>
            <div class="fields">
                <label for="id_username">Username:</label>
                {{ form.username }}
            </div>
            <div class="fields">
                <label for="id_email">Email:</label>
                {{ form.email }}
            </div>
            <div class="fields">
                <label for="id_password1">Password:</label>
                {{ form.password1 }}
            </div>
            <div class="fields">
                <label for="id_password2">Confirm Password:</label>
                {{ form.password2 }}
            </div>
            <button type="submit">Register</button>
            
        </form>
    </div>
    
</body>
</html> -->